# 强制指定键盘名称（覆盖 tidbit 默认值）
CONFIG_ZMK_KEYBOARD_NAME="numpad"
CONFIG_USB_DEVICE_PRODUCT="numpad"
CONFIG_BT_DEVICE_NAME="numpad"

# 关键！开机清除旧缓存（必须加）
# CONFIG_ZMK_SETTINGS_RESET_ON_START=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

#CONFIG_ZMK_DISPLAY=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y